version: "3.8"

services:
  dify-tools:
    build: .
    container_name: dify-tools
    ports:
      - "0.0.0.0:8502:8502"
    volumes:
      - ./plugins:/app/plugins
    networks:
      tools-net:
        ipv4_address: 172.25.0.10
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    pids_limit: 65535
    mem_limit: 2g
    cpus: 2.0
    restart: unless-stopped

networks:
  tools-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
